"use client";

import {
  createContext,
  useContext,
  useState,
  type ReactNode,
} from "react";

export type Language = "en" | "lg" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.tasks": "Tasks",
    "nav.budgets": "Budgets & Costs",
    "nav.materials": "Materials & Supplies",
    "nav.daily": "Daily Accountability",
    "nav.trends": "Trends & Insights",
    "nav.projects": "My Projects",
    "nav.settings": "Settings",
    "nav.help": "Help",
    "nav.logout": "Logout",
    "nav.more": "More",
    "nav.activeProject": "Active Project",
    "nav.switch": "Switch",
    "nav.whatsappConnected": "WhatsApp connected",
    "nav.connectWhatsapp": "Connect WhatsApp",
    "common.saving": "Saving…",
    "budget.editExpense": "Edit Expense",
    "budget.saveExpense": "Save",
    "landing.hero.title": "Message Anywhere.\nMonitor Everywhere.",
    "landing.hero.subtitle": "Use your favorite chat app to manage your construction project.",
    "landing.hero.cta": "Start Tracking",
    "landing.hero.demo": "Learn More",
    "landing.features.title": "Turn Site Messages Into\nStructured Control",
    "landing.features.subtitle": "JengaTrack transforms everyday construction updates into organized trackable data.",
    "landing.howitworks.title": "How It Works",
    "landing.howitworks.step1": "Send site updates",
    "landing.howitworks.step2": "Data Updates Automatically",
    "landing.howitworks.step3": "View or Request Insights",
    "landing.cta.title": "Build Smarter from Day One",
    "landing.cta.button": "Submit",
    "landing.hero.stats.contractors": "Active Contractors",
    "landing.hero.stats.ugxTracked": "UGX Tracked",
    "landing.hero.stats.expensesLogged": "Expenses Logged",
    "landing.hero.stats.satisfaction": "Satisfaction",
    "landing.nav.features": "Features",
    "landing.nav.pricing": "Pricing",
    "landing.nav.blog": "Blog",
    "landing.nav.contact": "Contact",
    "landing.nav.loginSignUp": "Login/SignUp",
    "landing.features.learnMore": "Learn More",
    "landing.features.manageProjects": "Manage Projects Through Chats",
    "landing.features.manageProjectsDesc": "Log purchases, labor payments, deliveries, and site updates by sending a simple message on WhatsApp or Telegram. No spreadsheets. No complicated tools. Just messages and results.",
    "landing.features.budgetUpdated": "Budget Updated Successfully",
    "landing.features.builtForReal": "Built for Real-World Construction",
    "landing.features.builtForRealDesc": "Updates can be sent in familiar language, simple text or voice notes. Reducing friction and improving adoption across teams.",
    "landing.features.fullVisibility": "Full Financial Visibility",
    "landing.features.fullVisibilityDesc": "Monitor spending in real time, compare actuals against budgets, and identify overspending before it becomes a crisis.",
    "landing.features.usersSpan": "Our users span across different countries in Africa.",
    "landing.features.actionableInsights": "Actionable Project Insights",
    "landing.features.actionableInsightsDesc": "Identify risks, track patterns, and operational inefficiencies. Transform raw data into structured insights that support faster, smarter decisions.",
    "landing.howitworks.desc1": "Message a purchase, task, or site activity in your chat app",
    "landing.howitworks.desc2": "JengaTrack logs the information and updates the project database instantly",
    "landing.howitworks.desc3": "Check progress on your dashboard or ask JengaTrack for reports directly in your chat",
    "landing.cta.waitlistDesc": "Join the JengaTrack waitlist to get early access, product updates, and behind-the-scenes progress as we prepare to launch.",
    "landing.cta.enterEmail": "Enter email address",
    "landing.cta.submitting": "Submitting…",
    "landing.cta.waitlistNote": "Be the first to try new features and receive occasional updates",
    "landing.footer.tagline": "Build With Clarity",
    "landing.footer.about": "About",
    "landing.footer.waitlist": "Waitlist",
    "landing.footer.privacyPolicy": "Privacy Policy",
    "landing.footer.termsConditions": "Terms & Conditions",
    "landing.footer.allRightsReserved": "All rights reserved.",
    "landing.footer.contact": "Contact",
    "landing.footer.location": "Location:",
    "landing.footer.email": "Email:",
    "auth.login.title": "Welcome Back",
    "auth.login.subtitle": "Log in to manage your construction projects",
    "auth.login.email": "Email Address",
    "auth.login.password": "Password",
    "auth.login.button": "Sign In",
    "auth.login.forgot": "Forgot password?",
    "auth.login.noaccount": "Don't have an account?",
    "auth.login.create": "Create one",
    "auth.register.title": "Create Account",
    "auth.register.subtitle": "Start managing your projects today",
    "auth.register.name": "Full Name",
    "auth.register.email": "Email Address",
    "auth.register.password": "Password",
    "auth.register.button": "Create Account",
    "auth.register.hasaccount": "Already have an account?",
    "auth.register.signin": "Sign in",
    "projects.title": "My Projects",
    "projects.new": "New Project",
    "projects.empty.title": "No projects yet",
    "projects.empty.subtitle": "Create your first project or\nconnect via WhatsApp",
    "projects.spent": "spent of",
    "projects.lastupdate": "Last update",
    "projects.noupdate": "No updates yet",
    "projects.active": "Active",
    "projects.completed": "Completed",
    "projects.select": "Select project",
    "dashboard.title": "Project Dashboard",
    "dashboard.progress": "Overall Progress",
    "dashboard.schedule": "Schedule Status",
    "dashboard.budget": "Budget Health",
    "dashboard.issues": "Active Issues",
    "dashboard.ontrack": "On Track",
    "dashboard.atrisk": "At Risk",
    "dashboard.delayed": "Delayed",
    "dashboard.allclear": "All clear ✅",
    "dashboard.lastupdate": "Last updated",
    "budget.title": "Budgets & Costs",
    "budget.total": "Total Budget",
    "budget.spent": "Total Spent",
    "budget.remaining": "Remaining",
    "budget.breakdown": "Budget Breakdown",
    "budget.monthly": "Spending by Month",
    "budget.recent": "Recent Transactions",
    "budget.vendors": "Vendor Breakdown",
    "budget.noexpenses": "No expenses logged yet",
    "materials.title": "Materials & Supplies",
    "materials.inventory": "Inventory",
    "materials.lowstock": "Low Stock Alerts",
    "materials.allgood": "✅ All materials well stocked",
    "materials.empty": "No materials tracked yet",
    "daily.title": "Daily Accountability",
    "daily.today": "Today's Status",
    "daily.active": "Active today",
    "daily.inactive": "No updates yet",
    "daily.workers": "Workers on site",
    "daily.workersCount": "workers",
    "daily.streak": "Current Streak",
    "daily.totaldays": "Total Active Days",
    "daily.avgworkers": "Avg Workers/Day",
    "daily.empty": "No daily updates yet",
    "trends.title": "Trends & Insights",
    "trends.spending": "Spending Trend",
    "trends.workers": "Worker Activity",
    "trends.materials": "Materials Usage",
    "trends.predictions": "Predictions",
    "trends.alerts": "Alerts",
    "trends.noissues": "✅ No issues detected",
    "trends.burnrate": "Weekly Burn Rate",
    "trends.runout": "Budget Runout Estimate",
    "trends.completion": "Project Completion",
    "trends.empty": "Trends will appear after a few\ndays of WhatsApp updates",
    "settings.title": "Settings",
    "settings.project": "Project Settings",
    "settings.profile": "Profile Settings",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.save": "Save Changes",
    "settings.saved": "Settings saved! ✅",
    "settings.danger": "Danger Zone",
    "settings.complete": "Mark project as completed",
    "settings.completeConfirm": "Mark project as completed?",
    "settings.completeDescription": "This will set the project status to completed. You won't be able to log new expenses or daily updates. You can still view all data.",
    "settings.completeConfirmButton": "Yes, mark as completed",
    "settings.projectname": "Project Name",
    "settings.location": "Location",
    "settings.budget": "Total Budget (UGX)",
    "settings.status": "Project Status",
    "settings.whatsapp": "WhatsApp Number",
    "settings.displayname": "Display Name",
    "settings.languageHint": "Select your preferred language",
    "settings.languageHintExtra": "Chagua lugha yako / Escolha seu idioma",
    "help.title": "Help & Support",
    "help.commands": "WhatsApp Commands",
    "help.faq": "FAQ",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.retry": "Try again",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.back": "Back",
    "common.next": "Next",
    "common.close": "Close",
    "common.search": "Search",
    "common.nodata": "No data available",
    "projects.loadError": "Failed to load projects",
    "projects.tryAgain": "Try again",
    "projects.emptySubtitleLong": "Create your first project or connect via WhatsApp to set up automatically.",
    "projects.createNew": "Create New Project",
    "projects.orWhatsApp": "Or WhatsApp us at",
    "projects.toGetStarted": "to get started.",
    "projects.backToProjects": "Back to Projects",
    "projects.createFirst": "Create your first project",
    "projects.selectProjectBudget": "Select a project from the sidebar or dashboard to view budget and expenses.",
    "projects.createFirstBudget": "Create your first project to track budget and expenses.",
    "projects.toastCreated": "Project created",
    "projects.toastCreatedDesc": "has been created successfully.",
    "projects.createFailed": "Failed to create project",
    "projects.modalTitle": "New Project",
    "projects.projectName": "Project name",
    "projects.projectType": "Project type",
    "projects.residential": "Residential",
    "projects.commercial": "Commercial",
    "projects.other": "Other",
    "projects.locationPlaceholder": "City or address",
    "projects.startDate": "Start date",
    "projects.totalBudgetUgx": "Total budget (UGX)",
    "projects.whatsappLink": "WhatsApp number to link",
    "projects.creating": "Creating…",
    "projects.createProject": "Create Project",
    "budget.noProjectSelect": "Select a project from the sidebar or dashboard to view budget and expenses.",
    "budget.noProjectCreate": "Create your first project to track budget and expenses.",
    "budget.budgetUsed": "Budget used",
    "budget.weeklyBurn": "Weekly burn",
    "budget.weeksRemaining": "Weeks remaining",
    "budget.noExpensesHint": "Send 'Bought cement for 200,000' via WhatsApp to start tracking.",
    "budget.noSpendingYet": "No spending history yet.",
    "budget.noSpendingHint": "Log expenses via WhatsApp to see monthly trends.",
    "budget.cumulativeCosts": "Cumulative Costs Over Time",
    "budget.noCumulativeHint": "Send an expense via WhatsApp to see your cumulative spend.",
    "budget.noTransactions": "No transactions yet.",
    "budget.noTransactionsHint": "Log an expense via WhatsApp or the dashboard to see it here.",
    "budget.noVendorYet": "No vendor data yet.",
    "budget.noVendorHint": "Expenses logged with a vendor name will appear here.",
    "budget.date": "Date",
    "budget.desc": "Description",
    "budget.amount": "Amount",
    "budget.category": "Category",
    "budget.source": "Source",
    "budget.manual": "Manual",
    "materials.noProjectSelect": "No project selected. Select a project from the sidebar or dashboard.",
    "materials.noProjectCreate": "Create your first project to track materials and inventory.",
    "materials.totalMaterials": "Total Materials",
    "materials.lowStockItems": "Low Stock Items",
    "materials.lastUpdated": "Last Updated",
    "materials.restockHint": "Consider restocking these materials.",
    "materials.allWellStocked": "All materials well stocked",
    "materials.low": "Low",
    "materials.good": "Good",
    "materials.medium": "Medium",
    "materials.lastUpdatedLabel": "Last updated",
    "materials.emptyHint": "Send 'Received 50 bags cement' or 'Used 5 bags for foundation' via WhatsApp to start tracking.",
    "daily.noProjectSelect": "No project selected. Select a project from the sidebar or dashboard.",
    "daily.noProjectCreate": "Create your first project to log daily updates.",
    "daily.activeToday": "Active today",
    "daily.noUpdatesYet": "No updates yet",
    "daily.workersLogged": "workers logged",
    "daily.activeDays": "Active Days",
    "daily.thisWeek": "This Week",
    "daily.photos": "Photos",
    "daily.activity60": "Activity (Last 60 Days)",
    "daily.recentActivity": "Recent Activity",
    "daily.sitePhotos": "Site Photos",
    "daily.noPhotosYet": "No photos yet.",
    "daily.noPhotosHint": "Send site photos via WhatsApp to see them here.",
    "daily.emptyHint": "Send '6 workers on site today' or 'Foundation 80% complete' via WhatsApp to start your activity log.",
    "trends.noProjectSelect": "No project selected. Select a project from the sidebar or dashboard.",
    "trends.noProjectCreate": "Create your first project to view trends and insights.",
    "trends.alertsAnomalies": "Alerts & Anomalies",
    "trends.noSpendingData": "No spending data yet.",
    "trends.noWorkerData": "No worker data yet.",
    "trends.avg": "Avg",
    "trends.peak": "Peak",
    "trends.topVendors": "Top Vendors",
    "trends.noMaterialsData": "No materials data yet.",
    "trends.increasing": "Increasing",
    "trends.decreasing": "Decreasing",
    "trends.stable": "Stable",
    "help.howToUseTitle": "Help & How To Use",
    "help.howToUseJenga": "How To Use JengaTrack",
    "help.saveNumber": "Save our WhatsApp number:",
    "help.sendJoin": "Send \"{code}\" to join the sandbox and get started",
    "help.textUpdates": "Text expenses, materials, and daily updates in plain language",
    "help.receiptPhotos": "Send receipt photos for automatic OCR scanning",
    "help.voiceNotes": "Send voice notes for transcription and logging",
    "help.commandsLike": "Use commands like \"How much have we spent?\" for budget summaries",
    "help.whatsappLabel": "WhatsApp number to message:",
    "help.joinCodeLabel": "Join code for sandbox:",
    "help.commandsRefTitle": "WhatsApp Commands Reference",
    "help.whatToSay": "What to say",
    "help.whatHappens": "What happens",
    "help.faqAddManager": "How do I add my manager to track updates?",
    "help.faqAddManagerAns": "Share the WhatsApp number with your manager. They just start texting and the bot handles the rest.",
    "help.faqDashboard": "How often does the dashboard update?",
    "help.faqDashboardAns": "Every 30 seconds automatically.",
    "help.faqVoice": "Can I use voice notes?",
    "help.faqVoiceAns": "Yes! Send any voice note and the bot will transcribe and process it.",
    "help.faqCurrencies": "What currencies are supported?",
    "help.faqCurrenciesAns": "UGX (Uganda), KES (Kenya), NGN (Nigeria). Receipt photos auto-convert to UGX.",
    "help.cmdExpense": "Logs expense",
    "help.cmdInventory": "Updates inventory",
    "help.cmdDaily": "Logs daily activity",
    "help.cmdProgress": "Updates progress",
    "help.cmdBudget": "Budget summary",
    "help.cmdInventoryCheck": "Inventory check",
    "help.cmdDelay": "Logs delay",
    "help.cmdSwitch": "Change active project",
    "help.cmdOCR": "OCR scan",
    "help.cmdVoice": "Transcribe & log",
    "auth.login.signingIn": "Signing in…",
    "auth.login.signupLink": "Sign up",
    "auth.register.whatsapp": "WhatsApp Number",
    "auth.register.confirmPassword": "Confirm Password",
    "auth.register.creating": "Creating account…",
    "auth.register.strength.weak": "Weak",
    "auth.register.strength.fair": "Fair",
    "auth.register.strength.good": "Good",
    "auth.register.strength.strong": "Strong",
    "auth.password.requirement.length": "At least 8 characters",
    "auth.password.requirement.lowercase": "One lowercase letter",
    "auth.password.requirement.uppercase": "One uppercase letter",
    "auth.password.requirement.digit": "One number",
    "auth.password.requirement.symbol": "One symbol (!@#$…)",
    "settings.passwordHint": "Current password required. New password must meet the same rules as sign-up.",
    "auth.forgotPassword.tagline": "We'll get you back in.",
    "auth.forgotPassword.title": "Reset your password",
    "auth.forgotPassword.subtitle": "Enter your email and we'll send a reset link",
    "auth.forgotPassword.button": "Send Reset Link",
    "auth.forgotPassword.sending": "Sending…",
    "auth.forgotPassword.backToLogin": "Back to login",
    "auth.forgotPassword.checkInbox": "Check your inbox",
    "auth.forgotPassword.resend": "Didn't receive it? Resend",
    "auth.forgotPassword.resending": "Resending…",
    "help.centerTitle": "Help Center",
    "help.tagline": "Everything you need to get the most out of JengaTrack.",
    "help.searchPlaceholder": "Search for help...",
    "help.whatsappBot": "WhatsApp Bot",
    "help.whatsappBotDesc": "Start chatting instantly",
    "help.openChat": "Open Chat",
    "help.viewDashboard": "View Dashboard",
    "help.viewDashboardDesc": "Go to your project",
    "help.goNow": "Go now",
    "help.sendFeedback": "Send Feedback",
    "help.sendFeedbackDesc": "Report a bug or suggestion",
    "help.emailUs": "Email us",
    "help.getStarted": "Get Started in 3 Steps",
    "help.step1Title": "Create your project",
    "help.step1Desc": "Sign up and create your first construction project with budget and location.",
    "help.step2Title": "Connect WhatsApp",
    "help.step2Desc": "Save our WhatsApp number and send your first message to link your account.",
    "help.step3Title": "Start logging",
    "help.step3Desc": "Send expenses, materials, worker counts and photos directly from WhatsApp.",
    "help.commandsDesc": "Just type naturally — here are some examples:",
    "help.faqTitle": "Frequently Asked Questions",
    "help.noResults": "No results found for",
    "help.stillNeedHelp": "Still need help?",
    "help.supportDesc": "Our team is available via WhatsApp during East Africa business hours.",
    "help.chatOnWhatsapp": "Chat on WhatsApp",
    "help.emailSupport": "Email Support",
    "help.responseTime": "Average response time: under 2 hours",
    "settings.subheader": "Manage your project configuration and profile details.",
    "settings.linkWhatsapp": "Link WhatsApp",
    "settings.linkWhatsappDesc": "Created a project via WhatsApp? Link your number to sync projects.",
    "settings.link": "Link",
    "settings.description": "Description",
    "settings.channelType": "Channel Type",
    "settings.directMessage": "Direct Message",
    "settings.groupChat": "Group Chat",
    "settings.saveProfile": "Save Profile",
    "settings.changePassword": "Change Password",
    "settings.completeProject": "Complete Project",
    "settings.markAsCompleted": "Mark as Completed",
    "settings.markCompleted": "Mark Completed",
    "settings.passwordUpdated": "Password updated successfully.",
    "settings.currentPassword": "Current Password",
    "settings.newPassword": "New Password",
    "settings.confirmNewPassword": "Confirm New Password",
    "settings.statusActive": "Active",
    "settings.statusCompleted": "Completed",
    "settings.statusOnHold": "On Hold",
    "materials.addMaterial": "Add material",
    "materials.headerSubtitle": "Inventory by material — stock levels, value, and low-stock alerts.",
    "materials.autoSync": "Auto-synced with WhatsApp — materials logged via chat appear here instantly.",
    "materials.lastSynced": "Last synced:",
    "materials.noMaterials": "No materials logged yet.",
    "materials.noMaterialsDesc": "Materials appear here automatically when you log purchases via WhatsApp, or add them manually using the button above.",
    "materials.addFirst": "Add your first material",
    "materials.colName": "Name",
    "materials.colCurrentStock": "Current stock",
    "materials.colUnitCost": "Unit cost",
    "materials.colTotalValue": "Total value",
    "materials.colLastPurchased": "Last purchased",
    "materials.colStatus": "Status",
    "materials.colStockLevel": "Stock level",
    "materials.colActions": "Actions",
    "materials.outOfStock": "Out of Stock",
    "materials.lowStock": "Low Stock",
    "materials.inStock": "In Stock",
    "materials.editMaterialTitle": "Edit material",
    "materials.editDesc": "Update quantity, costs, and low-stock threshold for this row.",
    "materials.addDesc": "Add stock to inventory. If the material name already exists, quantities are combined.",
    "materials.nameLbl": "Name",
    "materials.quantityLbl": "Quantity",
    "materials.unitLbl": "Unit",
    "materials.unitCostLbl": "Unit cost",
    "materials.thresholdLbl": "Low stock threshold",
    "materials.removeTitle": "Remove material?",
    "materials.removeSaving": "Removing…",
    "materials.totalInventoryValue": "Total inventory value",
    "projects.startFirst": "Start by creating your first project.",
    "projects.searchPlaceholder": "Search projects by name or location…",
    "projects.sortDate": "Sort: Date updated",
    "projects.sortName": "Sort: Name",
    "projects.sortProgress": "Sort: Progress",
    "projects.sortBudget": "Sort: Budget",
    "projects.noMatchTitle": "No matches",
    "projects.logFromWhatsapp": "Log from WhatsApp",
    "projects.chatOnWhatsapp": "Chat on WhatsApp",
    "projects.couldntLoad": "Couldn't load projects",
    "projects.kpiTotalProjects": "Total Projects",
    "projects.kpiTotalBudget": "Total Budget",
    "projects.kpiTotalSpent": "Total Spent",
    "projects.kpiActiveSites": "Active Sites",
    "projects.kpiAcrossAll": "Across all projects",
    "common.retry": "Retry",
    "common.cancel": "Cancel",
    "common.saving": "Saving…",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.refresh": "Refresh",
    "daily.header": "Daily Accountability",
    "daily.subheader": "Track site progress, worker attendance, and daily conditions.",
    "daily.daysRecorded": "days recorded",
    "daily.daysInARow": "days in a row",
    "daily.perDay": "per day",
    "daily.captured": "captured",
    "daily.daySummary": "Day summary",
    "daily.workersOnSite": "workers on site",
    "daily.weather": "Weather:",
    "daily.notes": "Notes:",
    "daily.failedToLoad": "Failed to load entries.",
    "daily.noWhatsappReports": "No WhatsApp chat reports for this day.",
    "daily.showAllActivity": "Show all activity",
    "daily.noActivity": "No activity logged for this day.",
    "daily.logActivity": "Log Activity",
    "daily.activityLast60": "Activity — last 60 days",
    "daily.logActivityTitle": "Log Activity",
    "daily.recordWhatHappened": "Record what happened on",
    "daily.entry": "Entry",
    "daily.remove": "Remove",
    "daily.addAnotherEntry": "+ Add another entry",
    "daily.saveActivity": "Save Activity",
    "daily.viewAll": "View all",
    "daily.viewHeatmap": "View heatmap",
    "daily.chatReports": "Chat reports",
    "daily.photos": "Photos",
    "daily.activityType.labourPayment": "Labour payment",
    "daily.activityType.delivery": "Delivery",
    "daily.activityType.taskCompletion": "Task completion",
    "daily.activityType.mediaUpload": "Media upload",
    "daily.activityType.staffing": "Staffing",
    "daily.activityType.financials": "Financials",
    "daily.activityType.activity": "Activity",
  },
  lg: {
    "nav.dashboard": "Pulezidenti",
    "nav.tasks": "Emirimu",
    "nav.budgets": "Ensimbi n'Empaliro",
    "nav.materials": "Ebintu n'Eby'okuzimba",
    "nav.daily": "Ebikolwa bya Buli Lunaku",
    "nav.trends": "Endabika n'Okunoonyereza",
    "nav.projects": "Emirimu Gyange",
    "nav.settings": "Entegeka",
    "nav.help": "Obuyamba",
    "nav.logout": "Funa",
    "nav.more": "Ebirala",
    "nav.activeProject": "Omurimo Omukola",
    "nav.switch": "Kyusa",
    "nav.whatsappConnected": "WhatsApp yaganyulwa",
    "nav.connectWhatsapp": "Gangana ku WhatsApp",
    "common.saving": "Nzachora…",
    "budget.editExpense": "Kyusa Ensimbi",
    "budget.saveExpense": "Zachora",
    "landing.hero.title": "Tuma Okubiri.\nLaba Wonna.",
    "landing.hero.subtitle": "Kozesa chat app yo okutebeza omurimo gwo gw'okuzimba.",
    "landing.hero.cta": "Tandika Okukwata",
    "landing.hero.demo": "Soma Ebirala",
    "landing.features.title": "Tebeza Emirimu gy'Okuzimba\nKu WhatsApp",
    "landing.features.subtitle": "JengaTrack ekyusa ennunula z'okuzimba mu data eteekateekeddwa.",
    "landing.howitworks.title": "Engeri Gye Ikola",
    "landing.howitworks.step1": "Tuma obubaka bwa WhatsApp",
    "landing.howitworks.step2": "Bot ekola ku bubaka bwo",
    "landing.howitworks.step3": "Dashboard enunulwa mangu",
    "landing.cta.title": "Tandika Ofudde",
    "landing.cta.button": "Tuma",
    "landing.hero.stats.contractors": "Abakozesi Abakola",
    "landing.hero.stats.ugxTracked": "UGX Ezikwata",
    "landing.hero.stats.expensesLogged": "Ensimbi Ezawandiikibwa",
    "landing.hero.stats.satisfaction": "Okwanagala",
    "landing.nav.features": "Ebintu",
    "landing.nav.pricing": "Obubaka",
    "landing.nav.blog": "Blog",
    "landing.nav.contact": "Okuyamba",
    "landing.nav.loginSignUp": "Yingira/Tonda",
    "landing.features.learnMore": "Soma Ebirala",
    "landing.features.manageProjects": "Tebeza Emirimu Ku Chat",
    "landing.features.manageProjectsDesc": "Wandiika ensimbi, abakoozi, n'ennunula ku WhatsApp oba Telegram. Teri spreadsheet. Nga tumu message.",
    "landing.features.budgetUpdated": "Ensimbi Zikyusiddwa",
    "landing.features.builtForReal": "Eteekeddwa Okuzimba",
    "landing.features.builtForRealDesc": "Tuma ennunula mu nnimi, obubaka oba voice note. Okutebenkanya n'okukozesa.",
    "landing.features.fullVisibility": "Okulaba Ensimbi Zonna",
    "landing.features.fullVisibilityDesc": "Laba ensimbi buli kiseera, kebera ne budget, olabe obuzibu mangu.",
    "landing.features.usersSpan": "Abakozesi baffe bali mu mawanga ga Afrika.",
    "landing.features.actionableInsights": "Okunoonyereza Kw'Emirimu",
    "landing.features.actionableInsightsDesc": "Laba obuzibu, endabika, n'ebikolebwa. Kyusa data mu biteekateeko.",
    "landing.howitworks.desc1": "Tuma ensimbi oba ennunula ku chat",
    "landing.howitworks.desc2": "JengaTrack awandiika n'akyoosa database mangu",
    "landing.howitworks.desc3": "Laba enkola ku dashboard oba buuza JengaTrack mu chat",
    "landing.cta.waitlistDesc": "Jjira ku waitlist ya JengaTrack okufuna early access n'ennunula.",
    "landing.cta.enterEmail": "Wandika email",
    "landing.cta.submitting": "Ntuma…",
    "landing.cta.waitlistNote": "Beera ow'okubanza okukebera n'ennunula.",
    "landing.footer.tagline": "Zimba N'Okulaba",
    "landing.footer.about": "Ebikwata",
    "landing.footer.waitlist": "Waitlist",
    "landing.footer.privacyPolicy": "Privacy Policy",
    "landing.footer.termsConditions": "Terms & Conditions",
    "landing.footer.allRightsReserved": "All rights reserved.",
    "landing.footer.contact": "Okuyamba",
    "landing.footer.location": "Ekifo:",
    "landing.footer.email": "Email:",
    "auth.login.title": "Tuukirira Nate",
    "auth.login.subtitle": "Yingira okutebeza emirimu gy'okuzimba",
    "auth.login.email": "Endagiriro y'Email",
    "auth.login.password": "Ekigambo ky'Okulinda",
    "auth.login.button": "Yingira",
    "auth.login.forgot": "Werabira ekigambo ky'okulinda?",
    "auth.login.noaccount": "Tolina kkaawunti?",
    "auth.login.create": "Tonda emu",
    "auth.register.title": "Tonda Kkaawunti",
    "auth.register.subtitle": "Tandika okutebeza emirimu gyo leero",
    "auth.register.name": "Erinnya Lyo Lyonna",
    "auth.register.email": "Endagiriro y'Email",
    "auth.register.password": "Ekigambo ky'Okulinda",
    "auth.register.button": "Tonda Kkaawunti",
    "auth.register.hasaccount": "Olina kkaawunti?",
    "auth.register.signin": "Yingira",
    "projects.title": "Emirimu Gyange",
    "projects.new": "Omurimo Omupya",
    "projects.empty.title": "Terina mirimo nawo",
    "projects.empty.subtitle": "Tonda omurimo gwo ogwa kubanga\noba gangana ku WhatsApp",
    "projects.spent": "yatumiibwa mu",
    "projects.lastupdate": "Ennunula ya omuvubuka",
    "projects.noupdate": "Terina nnunula nawo",
    "projects.active": "Yatandika",
    "projects.completed": "Yaggwaako",
    "projects.select": "Londa omurimo",
    "dashboard.title": "Pulezidenti w'Omurimo",
    "dashboard.progress": "Enkola Yonna",
    "dashboard.schedule": "Endabika y'Enteekateeka",
    "dashboard.budget": "Obulamu bw'Ensimbi",
    "dashboard.issues": "Ebizibu Ebiriko",
    "dashboard.ontrack": "Ku Kkubo",
    "dashboard.atrisk": "Mu Kabi",
    "dashboard.delayed": "Kuziyizibwa",
    "dashboard.allclear": "Buli kimu kituufu ✅",
    "dashboard.lastupdate": "Ennunula ya omuvubuka",
    "budget.title": "Ensimbi n'Empaliro",
    "budget.total": "Ensimbi Zonna",
    "budget.spent": "Ensimbi Ezatumiibwa",
    "budget.remaining": "Ezasigalawo",
    "budget.breakdown": "Okugabana kw'Ensimbi",
    "budget.monthly": "Okutumiibwa mu Mwezi",
    "budget.recent": "Obusuubuzi Obwakiiro",
    "budget.vendors": "Abatundisi Abalala",
    "budget.noexpenses": "Terina nsimbi yatumiibwa",
    "materials.title": "Ebintu n'Eby'okuzimba",
    "materials.inventory": "Ebintu Ebiriwo",
    "materials.lowstock": "Okumenyeeza kw'Ebintu",
    "materials.allgood": "✅ Ebintu byonna biriwo",
    "materials.empty": "Terina bintu byakwatibwa",
    "daily.title": "Ebikolwa bya Buli Lunaku",
    "daily.today": "Endabika ya Leero",
    "daily.active": "Ekola leero",
    "daily.inactive": "Terina nnunula nawo",
    "daily.workers": "Abakoozi Ku Kifo",
    "daily.workersCount": "abakoozi",
    "daily.streak": "Ennaku Entalirivu",
    "daily.totaldays": "Ennaku Zonna Ezikoleddwa",
    "daily.avgworkers": "Ab'okulaba mu lunaku",
    "daily.empty": "Terina bikolwa bya buli lunaku",
    "trends.title": "Endabika n'Okunoonyereza",
    "trends.spending": "Endabika y'Okutumiibwa",
    "trends.workers": "Ebikolwa by'Abakoozi",
    "trends.materials": "Okutumiibwa kw'Ebintu",
    "trends.predictions": "Okubuulira Ebizaajja",
    "trends.alerts": "Okumenyeeza",
    "trends.noissues": "✅ Terina bizibu byakiririzibwa",
    "trends.burnrate": "Enkola y'Ensimbi mu Wiiki",
    "trends.runout": "Ensimbi Mazima Lini",
    "trends.completion": "Omurimo Gwagwaako Lini",
    "trends.empty": "Endabika ejja ng'olaba ennaku\nennaka ez'ennunula ku WhatsApp",
    "settings.title": "Entegeka",
    "settings.project": "Entegeka y'Omurimo",
    "settings.profile": "Entegeka y'Omuntu",
    "settings.language": "Olulimi",
    "settings.theme": "Endabika",
    "settings.save": "Zachora Ennunula",
    "settings.saved": "Entegeka Zachoredwa! ✅",
    "settings.danger": "Ekifo Ky'Obubuubi",
    "settings.complete": "Labika omurimo gwagwaako",
    "settings.completeConfirm": "Labika omurimo gwagwaako?",
    "settings.completeDescription": "Omurimo gujja kukolebwa nga gwagwaako. Toliba kuwandiika nsimbi ennunula oba ennunula z'ennaku. Kyokka osobola okulaba data yonna.",
    "settings.completeConfirmButton": "Yee, labika gwagwaako",
    "settings.projectname": "Erinnya ly'Omurimo",
    "settings.location": "Ekifo",
    "settings.budget": "Ensimbi Zonna (UGX)",
    "settings.status": "Endabika y'Omurimo",
    "settings.whatsapp": "Namba ya WhatsApp",
    "settings.displayname": "Erinnya ly'Okulagirako",
    "settings.languageHint": "Londa olulimi lwo",
    "settings.languageHintExtra": "Chagua lugha yako / Escolha seu idioma",
    "help.title": "Obuyamba n'Enyigiriza",
    "help.commands": "Ebiragiro bya WhatsApp",
    "help.faq": "Ebibuuzo Ebibuuzibwa Ennyi",
    "common.loading": "Tekebeza...",
    "common.error": "Wabaawo ekizibu",
    "common.retry": "Gezaako Nate",
    "common.save": "Zachora",
    "common.cancel": "Sazaamu",
    "common.confirm": "Kakasa",
    "common.delete": "Sazaamu",
    "common.edit": "Kyusa",
    "common.back": "Ddayo Eweyo",
    "common.next": "Endeera",
    "common.close": "Ggalawo",
    "common.search": "Noonya",
    "common.nodata": "Terina data nawo",
    "projects.loadError": "Okulonda emirimu tekukkirizibwa",
    "projects.tryAgain": "Gezaako Nate",
    "projects.emptySubtitleLong": "Tonda omurimo gwo oba gangana ku WhatsApp.",
    "projects.createNew": "Tonda Omurimo Omupya",
    "projects.orWhatsApp": "Oba tuma ku",
    "projects.toGetStarted": "okutandika.",
    "projects.backToProjects": "Ddayo Ku Mirimo",
    "projects.createFirst": "Tonda omurimo gwo ogwa kubanga",
    "projects.selectProjectBudget": "Londa omurimo ku sidebar oba dashboard.",
    "projects.createFirstBudget": "Tonda omurimo gwo okukwata ensimbi.",
    "projects.toastCreated": "Omurimo gwatondeddwa",
    "projects.toastCreatedDesc": "gwatondeddwa bulungi.",
    "projects.createFailed": "Okutonda omurimo tekukkirizibwa",
    "projects.modalTitle": "Omurimo Omupya",
    "projects.projectName": "Erinnya ly'Omurimo",
    "projects.projectType": "Ennono y'Omurimo",
    "projects.residential": "Residential",
    "projects.commercial": "Commercial",
    "projects.other": "Ebirala",
    "projects.locationPlaceholder": "Ekibuga oba ekifo",
    "projects.startDate": "Olunaku lw'okutandika",
    "projects.totalBudgetUgx": "Ensimbi zonna (UGX)",
    "projects.whatsappLink": "Namba ya WhatsApp",
    "projects.creating": "Nkutonda…",
    "projects.createProject": "Tonda Omurimo",
    "budget.noProjectSelect": "Londa omurimo ku sidebar oba dashboard.",
    "budget.noProjectCreate": "Tonda omurimo gwo okukwata ensimbi.",
    "budget.budgetUsed": "Ensimbi ezikozesebwa",
    "budget.weeklyBurn": "Ensimbi mu wiiki",
    "budget.weeksRemaining": "Wiiki zisigala",
    "budget.noExpensesHint": "Tuma 'Bought cement for 200,000' ku WhatsApp.",
    "budget.noSpendingYet": "Terina mbuuzo y'ensimbi.",
    "budget.noSpendingHint": "Tuma ensimbi ku WhatsApp.",
    "budget.cumulativeCosts": "Ensimbi Ezikozesebwa Mu Biseera",
    "budget.noCumulativeHint": "Tuma ensimbi ku WhatsApp.",
    "budget.noTransactions": "Terina busuubuzi nawo.",
    "budget.noTransactionsHint": "Tuma ensimbi ku WhatsApp oba dashboard.",
    "budget.noVendorYet": "Terina batundisi nawo.",
    "budget.noVendorHint": "Ensimbi ezirina omutundisi zijja wano.",
    "budget.date": "Olunaku",
    "budget.desc": "Ennono",
    "budget.amount": "Ensimbi",
    "budget.category": "Ennono",
    "budget.source": "Obulabu",
    "budget.manual": "Mukono",
    "materials.noProjectSelect": "Tolina murimo olondeddwa. Londa ku sidebar.",
    "materials.noProjectCreate": "Tonda omurimo gwo okukwata ebintu.",
    "materials.totalMaterials": "Ebintu Byonna",
    "materials.lowStockItems": "Ebintu Ebikadde",
    "materials.lastUpdated": "Ennunula Ya Omuvubuka",
    "materials.restockHint": "Lowooza okuzza ebintu.",
    "materials.allWellStocked": "Ebintu byonna biriwo",
    "materials.low": "Kadde",
    "materials.good": "Bulungi",
    "materials.medium": "Wakati",
    "materials.lastUpdatedLabel": "Ennunula ya omuvubuka",
    "materials.emptyHint": "Tuma 'Received 50 bags cement' ku WhatsApp.",
    "daily.noProjectSelect": "Tolina murimo olondeddwa. Londa ku sidebar.",
    "daily.noProjectCreate": "Tonda omurimo gwo okuloga ennunula.",
    "daily.activeToday": "Ekola leero",
    "daily.noUpdatesYet": "Terina nnunula nawo",
    "daily.workersLogged": "abakoozi balogeddwa",
    "daily.activeDays": "Ennaku Ezikoleddwa",
    "daily.thisWeek": "Wiiki Eno",
    "daily.photos": "Ebirango",
    "daily.activity60": "Ebikolwa (Ennaku 60)",
    "daily.recentActivity": "Ebikolwa Byakiiro",
    "daily.sitePhotos": "Ebirango by'Ekifo",
    "daily.noPhotosYet": "Terina birango nawo.",
    "daily.noPhotosHint": "Tuma birango ku WhatsApp.",
    "daily.emptyHint": "Tuma '6 workers on site today' ku WhatsApp.",
    "trends.noProjectSelect": "Tolina murimo olondeddwa. Londa ku sidebar.",
    "trends.noProjectCreate": "Tonda omurimo gwo okulaba endabika.",
    "trends.alertsAnomalies": "Okumenyeeza",
    "trends.noSpendingData": "Terina data y'ensimbi.",
    "trends.noWorkerData": "Terina data y'abakoozi.",
    "trends.avg": "Wakati",
    "trends.peak": "Okuwanuka",
    "trends.topVendors": "Abatundisi Abasinga",
    "trends.noMaterialsData": "Terina data y'ebintu.",
    "trends.increasing": "Okwonoona",
    "trends.decreasing": "Okusazaala",
    "trends.stable": "Nnamaddala",
    "help.howToUseTitle": "Obuyamba n'Engeri Y'okukozesa",
    "help.howToUseJenga": "Kozesa JengaTrack",
    "help.saveNumber": "Tereka namba yaffe ya WhatsApp:",
    "help.sendJoin": "Tuma \"{code}\" okujjira ne kutandika",
    "help.textUpdates": "Tuma ensimbi, ebintu n'ennunula.",
    "help.receiptPhotos": "Tuma birango by'ensimbi.",
    "help.voiceNotes": "Tuma voice note.",
    "help.commandsLike": "Kozesa ebiragiro nk 'How much have we spent?'",
    "help.whatsappLabel": "Namba ya WhatsApp:",
    "help.joinCodeLabel": "Koodi y'okujjira:",
    "help.commandsRefTitle": "Ebiragiro bya WhatsApp",
    "help.whatToSay": "Ky'osobola okugamba",
    "help.whatHappens": "Ky'ekoleka",
    "help.faqAddManager": "Nnongera manager wange ntabe?",
    "help.faqAddManagerAns": "Gaba namba ya WhatsApp. Bot akola.",
    "help.faqDashboard": "Dashboard ekyusibwa buli lwaki?",
    "help.faqDashboardAns": "Buli ssekendi 30.",
    "help.faqVoice": "Nsobola okukozesa voice note?",
    "help.faqVoiceAns": "Yee! Tuma voice note, bot asannyalaza.",
    "help.faqCurrencies": "Ensimbi ziri zitya?",
    "help.faqCurrenciesAns": "UGX, KES, NGN. Receipt photos zikyusibwa mu UGX.",
    "help.cmdExpense": "Okuloga ensimbi",
    "help.cmdInventory": "Okukyusa ebintu",
    "help.cmdDaily": "Okuloga ebikolwa",
    "help.cmdProgress": "Okukyusa enkola",
    "help.cmdBudget": "Ensimbi",
    "help.cmdInventoryCheck": "Okulaba ebintu",
    "help.cmdDelay": "Okuloga kuziyizibwa",
    "help.cmdSwitch": "Kyusa omurimo",
    "help.cmdOCR": "OCR",
    "help.cmdVoice": "Okutandika",
    "auth.login.signingIn": "Twingira…",
    "auth.login.signupLink": "Tonda",
    "auth.register.whatsapp": "Namba ya WhatsApp",
    "auth.register.confirmPassword": "Kakasa Ekigambo",
    "auth.register.creating": "Nkutonda kkaawunti…",
    "auth.register.strength.weak": "Butali",
    "auth.register.strength.fair": "Wakati",
    "auth.register.strength.good": "Bulungi",
    "auth.register.strength.strong": "Maanyi",
    "auth.password.requirement.length": "Wakati ebitundu 8",
    "auth.password.requirement.lowercase": "Ennukuta entonotono",
    "auth.password.requirement.uppercase": "Ennukuta ennene",
    "auth.password.requirement.digit": "Namba emu",
    "auth.password.requirement.symbol": "Akabonero (!@#$…)",
    "settings.passwordHint": "Weetaaga ekigambo kya leero. Ekigambo ekipya kiteekwa okutuukiriza amateeka g'okwewandiisa.",
    "auth.forgotPassword.tagline": "Tujja kukuddayo.",
    "auth.forgotPassword.title": "Kyusa Ekigambo ky'Okulinda",
    "auth.forgotPassword.subtitle": "Wandika email n'otumire omukago",
    "auth.forgotPassword.button": "Tuma Omukago",
    "auth.forgotPassword.sending": "Ntuma…",
    "auth.forgotPassword.backToLogin": "Ddayo ku Kuyingira",
    "auth.forgotPassword.checkInbox": "Kebera Email yo",
    "auth.forgotPassword.resend": "Tokirizidde? Tumamu",
    "auth.forgotPassword.resending": "Ntumamu…",
    "help.centerTitle": "Ekifo ky'Obuyamba",
    "help.tagline": "Byonna eby'okukozesa JengaTrack bulungi.",
    "help.searchPlaceholder": "Noonya obuyamba...",
    "help.whatsappBot": "Bot ya WhatsApp",
    "help.whatsappBotDesc": "Tandika okubuulirako",
    "help.openChat": "Fumba Enkokola",
    "help.viewDashboard": "Laba Dashboard",
    "help.viewDashboardDesc": "Genda ku murimo gwo",
    "help.goNow": "Genda Kaakano",
    "help.sendFeedback": "Tuma Empuliziganya",
    "help.sendFeedbackDesc": "Mabikira akakwero oba ekyakwetaba",
    "help.emailUs": "Tuumire Email",
    "help.getStarted": "Tandika mu Nnyonyi 3",
    "help.step1Title": "Tonda Omurimo gwo",
    "help.step1Desc": "Tonda kkaawunti ne kukola omurimo gwo ogwa kubanga.",
    "help.step2Title": "Gangana ku WhatsApp",
    "help.step2Desc": "Tereka namba yaffe ne kutuma obubaka bwo bwa kubanga.",
    "help.step3Title": "Tandika Okuloga",
    "help.step3Desc": "Tuma ensimbi, ebintu, abakoozi n'ebifaananyi ku WhatsApp.",
    "help.commandsDesc": "Wandika nga obadde obuulira — wano mw'okulaba:",
    "help.faqTitle": "Ebibuuzo Ebibuuzibwa Ennyi",
    "help.noResults": "Terina bikutuuka ku",
    "help.stillNeedHelp": "Okyali n'Obuyamba?",
    "help.supportDesc": "Timu yaffe erikutegereza ku WhatsApp mu biseera by'omulimu.",
    "help.chatOnWhatsapp": "Buulirako ku WhatsApp",
    "help.emailSupport": "Obuyamba bw'Email",
    "help.responseTime": "Obudde bw'okwetaba: wansi wa saawa 2",
    "settings.subheader": "Tebeza entegeka y'omurimo gwo n'ebyobutuufu.",
    "settings.linkWhatsapp": "Gangana ku WhatsApp",
    "settings.linkWhatsappDesc": "Watorondeedde omurimo ku WhatsApp? Gangana namba yo.",
    "settings.link": "Gangana",
    "settings.description": "Ennono",
    "settings.channelType": "Ennono y'Ekizindalo",
    "settings.directMessage": "Bubaka Bujuli",
    "settings.groupChat": "Enkokola y'Ekibuga",
    "settings.saveProfile": "Zachora Omuntu",
    "settings.changePassword": "Kyusa Ekigambo ky'Okulinda",
    "settings.completeProject": "Maliriza Omurimo",
    "settings.markAsCompleted": "Labika Gwagwaako",
    "settings.markCompleted": "Labika Gwagwaako",
    "settings.passwordUpdated": "Ekigambo kyakyusiddwa bulungi.",
    "settings.currentPassword": "Ekigambo Ekiriko",
    "settings.newPassword": "Ekigambo Ekipya",
    "settings.confirmNewPassword": "Kakasa Ekigambo Ekipya",
    "settings.statusActive": "Yatandika",
    "settings.statusCompleted": "Yaggwaako",
    "settings.statusOnHold": "Okuzikirira",
    "materials.addMaterial": "Gagga Ekikozesebwa",
    "materials.headerSubtitle": "Ebintu mu nkiiko — amaanyi ga stock n'eby'okulabirira.",
    "materials.autoSync": "Kikutuuka ku WhatsApp — ebintu ebiloggedwa ku chat biragwa wano amangu.",
    "materials.lastSynced": "Yalabibwa omulundi oguwedde:",
    "materials.noMaterials": "Terina bikozesebwa byalalogedwa.",
    "materials.noMaterialsDesc": "Ebikozesebwa biragwa wano amangu bw'ogula ku WhatsApp, oba obiyongera ku kibuttoni ky'okulungu.",
    "materials.addFirst": "Gagga ekikozesebwa kyo ekisooka",
    "materials.colName": "Erinnya",
    "materials.colCurrentStock": "Stock Ekiriko",
    "materials.colUnitCost": "Omuwendo gw'Ekimu",
    "materials.colTotalValue": "Omuwendo Gwonna",
    "materials.colLastPurchased": "Yagundiibwa Omulundi Oguwedde",
    "materials.colStatus": "Endagaano",
    "materials.colStockLevel": "Ekifo kya Stock",
    "materials.colActions": "Ebikolwa",
    "materials.outOfStock": "Wayisaamu",
    "materials.lowStock": "Stock Ntono",
    "materials.inStock": "Walimu Stock",
    "materials.editMaterialTitle": "Kyusa Ekikozesebwa",
    "materials.editDesc": "Kyusa obungi, omuwendo, n'ekifo ky'okulabirira.",
    "materials.addDesc": "Yongera stock mu nkiiko.",
    "materials.nameLbl": "Erinnya",
    "materials.quantityLbl": "Obungi",
    "materials.unitLbl": "Emitindo",
    "materials.unitCostLbl": "Omuwendo gw'Ekimu",
    "materials.thresholdLbl": "Ekifo ky'Okulabirira Stock Entono",
    "materials.removeTitle": "Ggyawo Ekikozesebwa?",
    "materials.removeSaving": "Kiggyebwa…",
    "materials.totalInventoryValue": "Omuwendo Gwonna gw'Ebintu",
    "projects.startFirst": "Tandika ne kutonda omurimo gwo ogwa kubanga.",
    "projects.searchPlaceholder": "Noonya emirimo mu linnya oba ahantu…",
    "projects.sortDate": "Tegeka: Olunaku Olwakukyusibwa",
    "projects.sortName": "Tegeka: Erinnya",
    "projects.sortProgress": "Tegeka: Enkyuka",
    "projects.sortBudget": "Tegeka: Budget",
    "projects.noMatchTitle": "Terina Bikutuuka",
    "projects.logFromWhatsapp": "Loga ku WhatsApp",
    "projects.chatOnWhatsapp": "Buulirako ku WhatsApp",
    "projects.couldntLoad": "Teeyinza Kutwala Emirimo",
    "projects.kpiTotalProjects": "Emirimo Gyonna",
    "projects.kpiTotalBudget": "Budget Yonna",
    "projects.kpiTotalSpent": "Byonna Ebyasasulibwa",
    "projects.kpiActiveSites": "Aw'Omulimu Abali mu Nkola",
    "projects.kpiAcrossAll": "Mu mirimo gyonna",
    "common.retry": "Gezaamu",
    "common.cancel": "Sazaamu",
    "common.saving": "Kubika…",
    "common.save": "Zachora",
    "common.delete": "Sazaamu",
    "common.refresh": "Kyusakyusa",
    "daily.header": "Obutuufu bwa Buli Lunaku",
    "daily.subheader": "Kebera enkyuka ya kifo, abakoozi n'ebigendawo buli lunaku.",
    "daily.daysRecorded": "ennaku ezilogedwa",
    "daily.daysInARow": "ennaku ezirimu",
    "daily.perDay": "ku lunaku",
    "daily.captured": "ezifotoleddwa",
    "daily.daySummary": "Enkuukuuma y'Olunaku",
    "daily.workersOnSite": "abakoozi ku kifo",
    "daily.weather": "Obudde:",
    "daily.notes": "Ebiwandiiko:",
    "daily.failedToLoad": "Teeyinza kutwala ebintu.",
    "daily.noWhatsappReports": "Terina bibuuzo bya WhatsApp olunaku oluno.",
    "daily.showAllActivity": "Laba ebikolwa byonna",
    "daily.noActivity": "Terina bikolwa ebyalogedwa olunaku oluno.",
    "daily.logActivity": "Loga Ebikolwa",
    "daily.activityLast60": "Ebikolwa — ennaku 60 eziyise",
    "daily.logActivityTitle": "Loga Ebikolwa",
    "daily.recordWhatHappened": "Wandika ebyabaawo ku",
    "daily.entry": "Ekikyuusa",
    "daily.remove": "Ggyawo",
    "daily.addAnotherEntry": "+ Yongera ekikyuusa",
    "daily.saveActivity": "Zachora Ebikolwa",
    "daily.viewAll": "Laba Byonna",
    "daily.viewHeatmap": "Laba Heatmap",
    "daily.chatReports": "Bibuuzo bya Chat",
    "daily.photos": "Ebifaananyi",
    "daily.activityType.labourPayment": "Ssente z'Abakoozi",
    "daily.activityType.delivery": "Okutwalibwa",
    "daily.activityType.taskCompletion": "Okkumaliriza Omukolo",
    "daily.activityType.mediaUpload": "Okutumira Ebifaananyi",
    "daily.activityType.staffing": "Abakoozi",
    "daily.activityType.financials": "Ensimbi",
    "daily.activityType.activity": "Ebikolwa",
  },
  pt: {
    "nav.dashboard": "Painel",
    "nav.tasks": "Tarefas",
    "nav.budgets": "Orçamentos e Custos",
    "nav.materials": "Materiais e Suprimentos",
    "nav.daily": "Prestação de Contas Diária",
    "nav.trends": "Tendências e Insights",
    "nav.projects": "Meus Projetos",
    "nav.settings": "Configurações",
    "nav.help": "Ajuda",
    "nav.logout": "Sair",
    "nav.more": "Mais",
    "nav.activeProject": "Projeto Ativo",
    "nav.switch": "Trocar",
    "nav.whatsappConnected": "WhatsApp conectado",
    "nav.connectWhatsapp": "Conectar WhatsApp",
    "common.saving": "Salvando…",
    "budget.editExpense": "Editar Despesa",
    "budget.saveExpense": "Salvar",
    "landing.hero.title": "Mensagem em Qualquer Lugar.\nMonitore em Todo Lugar.",
    "landing.hero.subtitle": "Use seu app de chat favorito para gerenciar seu projeto de construção.",
    "landing.hero.cta": "Começar a Rastrear",
    "landing.hero.demo": "Saiba Mais",
    "landing.features.title": "Gerencie Projetos de Construção\npelo WhatsApp",
    "landing.features.subtitle": "Rastreie orçamentos, materiais e progresso diário — tudo pelo WhatsApp.",
    "landing.howitworks.title": "Como Funciona",
    "landing.howitworks.step1": "Envie uma mensagem no WhatsApp",
    "landing.howitworks.step2": "Bot processa sua atualização",
    "landing.howitworks.step3": "Painel atualiza instantaneamente",
    "landing.cta.title": "Construa com Inteligência desde o Primeiro Dia",
    "landing.cta.button": "Enviar",
    "landing.hero.stats.contractors": "Construtores Ativos",
    "landing.hero.stats.ugxTracked": "UGX Rastreados",
    "landing.hero.stats.expensesLogged": "Despesas Registradas",
    "landing.hero.stats.satisfaction": "Satisfação",
    "landing.nav.features": "Recursos",
    "landing.nav.pricing": "Preços",
    "landing.nav.blog": "Blog",
    "landing.nav.contact": "Contato",
    "landing.nav.loginSignUp": "Entrar/Cadastrar",
    "landing.features.learnMore": "Saiba Mais",
    "landing.features.manageProjects": "Gerencie Projetos pelo Chat",
    "landing.features.manageProjectsDesc": "Registre compras, pagamentos de mão de obra, entregas e atualizações de obra enviando uma mensagem no WhatsApp ou Telegram. Sem planilhas. Só mensagens e resultados.",
    "landing.features.budgetUpdated": "Orçamento Atualizado com Sucesso",
    "landing.features.builtForReal": "Feito para Construção Real",
    "landing.features.builtForRealDesc": "Atualizações podem ser enviadas em linguagem simples, texto ou notas de voz. Menos fricção e mais adoção pelas equipes.",
    "landing.features.fullVisibility": "Visibilidade Financeira Total",
    "landing.features.fullVisibilityDesc": "Acompanhe gastos em tempo real, compare com orçamentos e identifique excessos antes que virem crise.",
    "landing.features.usersSpan": "Nossos usuários estão em vários países da África.",
    "landing.features.actionableInsights": "Insights Acionáveis",
    "landing.features.actionableInsightsDesc": "Identifique riscos, padrões e ineficiências. Transforme dados em insights estruturados para decisões mais rápidas.",
    "landing.howitworks.desc1": "Envie uma compra, tarefa ou atividade de obra no seu chat",
    "landing.howitworks.desc2": "O JengaTrack registra e atualiza o banco de dados do projeto na hora",
    "landing.howitworks.desc3": "Veja o progresso no painel ou peça relatórios ao JengaTrack direto no chat",
    "landing.cta.waitlistDesc": "Junte-se à lista de espera do JengaTrack para acesso antecipado, atualizações e novidades antes do lançamento.",
    "landing.cta.enterEmail": "Digite seu e-mail",
    "landing.cta.submitting": "Enviando…",
    "landing.cta.waitlistNote": "Seja o primeiro a testar novos recursos e receber atualizações.",
    "landing.footer.tagline": "Construa com Clareza",
    "landing.footer.about": "Sobre",
    "landing.footer.waitlist": "Lista de Espera",
    "landing.footer.privacyPolicy": "Política de Privacidade",
    "landing.footer.termsConditions": "Termos e Condições",
    "landing.footer.allRightsReserved": "Todos os direitos reservados.",
    "landing.footer.contact": "Contato",
    "landing.footer.location": "Localização:",
    "landing.footer.email": "E-mail:",
    "auth.login.title": "Bem-vindo de Volta",
    "auth.login.subtitle": "Faça login para gerenciar seus projetos de construção",
    "auth.login.email": "Endereço de E-mail",
    "auth.login.password": "Senha",
    "auth.login.button": "Entrar",
    "auth.login.forgot": "Esqueceu a senha?",
    "auth.login.noaccount": "Não tem uma conta?",
    "auth.login.create": "Criar uma",
    "auth.register.title": "Criar Conta",
    "auth.register.subtitle": "Comece a gerenciar seus projetos hoje",
    "auth.register.name": "Nome Completo",
    "auth.register.email": "Endereço de E-mail",
    "auth.register.password": "Senha",
    "auth.register.button": "Criar Conta",
    "auth.register.hasaccount": "Já tem uma conta?",
    "auth.register.signin": "Entrar",
    "projects.title": "Meus Projetos",
    "projects.new": "Novo Projeto",
    "projects.empty.title": "Nenhum projeto ainda",
    "projects.empty.subtitle": "Crie seu primeiro projeto ou\nconecte via WhatsApp",
    "projects.spent": "gasto de",
    "projects.lastupdate": "Última atualização",
    "projects.noupdate": "Sem atualizações ainda",
    "projects.active": "Ativo",
    "projects.completed": "Concluído",
    "projects.select": "Selecionar projeto",
    "dashboard.title": "Painel do Projeto",
    "dashboard.progress": "Progresso Geral",
    "dashboard.schedule": "Status do Cronograma",
    "dashboard.budget": "Saúde do Orçamento",
    "dashboard.issues": "Problemas Ativos",
    "dashboard.ontrack": "No Prazo",
    "dashboard.atrisk": "Em Risco",
    "dashboard.delayed": "Atrasado",
    "dashboard.allclear": "Tudo certo ✅",
    "dashboard.lastupdate": "Última atualização",
    "budget.title": "Orçamentos e Custos",
    "budget.total": "Orçamento Total",
    "budget.spent": "Total Gasto",
    "budget.remaining": "Restante",
    "budget.breakdown": "Detalhamento do Orçamento",
    "budget.monthly": "Gastos por Mês",
    "budget.recent": "Transações Recentes",
    "budget.vendors": "Detalhamento por Fornecedor",
    "budget.noexpenses": "Nenhuma despesa registrada",
    "materials.title": "Materiais e Suprimentos",
    "materials.inventory": "Inventário",
    "materials.lowstock": "Alertas de Estoque Baixo",
    "materials.allgood": "✅ Todos os materiais em estoque",
    "materials.empty": "Nenhum material rastreado ainda",
    "daily.title": "Prestação de Contas Diária",
    "daily.today": "Status de Hoje",
    "daily.active": "Ativo hoje",
    "daily.inactive": "Sem atualizações ainda",
    "daily.workers": "Trabalhadores no Local",
    "daily.workersCount": "trabalhadores",
    "daily.streak": "Sequência Atual",
    "daily.totaldays": "Total de Dias Ativos",
    "daily.avgworkers": "Média de Trabalhadores/Dia",
    "daily.empty": "Nenhuma atualização diária ainda",
    "trends.title": "Tendências e Insights",
    "trends.spending": "Tendência de Gastos",
    "trends.workers": "Atividade de Trabalhadores",
    "trends.materials": "Uso de Materiais",
    "trends.predictions": "Previsões",
    "trends.alerts": "Alertas",
    "trends.noissues": "✅ Nenhum problema detectado",
    "trends.burnrate": "Taxa de Gasto Semanal",
    "trends.runout": "Estimativa de Esgotamento",
    "trends.completion": "Conclusão do Projeto",
    "trends.empty": "Tendências aparecerão após alguns\ndias de atualizações no WhatsApp",
    "settings.title": "Configurações",
    "settings.project": "Configurações do Projeto",
    "settings.profile": "Configurações do Perfil",
    "settings.language": "Idioma",
    "settings.theme": "Tema",
    "settings.save": "Salvar Alterações",
    "settings.saved": "Configurações salvas! ✅",
    "settings.danger": "Zona de Perigo",
    "settings.complete": "Marcar projeto como concluído",
    "settings.completeConfirm": "Marcar projeto como concluído?",
    "settings.completeDescription": "Isso definirá o status do projeto como concluído. Você não poderá registrar novas despesas ou atualizações diárias. Ainda poderá ver todos os dados.",
    "settings.completeConfirmButton": "Sim, marcar como concluído",
    "settings.projectname": "Nome do Projeto",
    "settings.location": "Localização",
    "settings.budget": "Orçamento Total (UGX)",
    "settings.status": "Status do Projeto",
    "settings.whatsapp": "Número do WhatsApp",
    "settings.displayname": "Nome de Exibição",
    "settings.languageHint": "Selecione seu idioma preferido",
    "settings.languageHintExtra": "Chagua lugha yako / Escolha seu idioma",
    "help.title": "Ajuda e Suporte",
    "help.commands": "Comandos do WhatsApp",
    "help.faq": "Perguntas Frequentes",
    "common.loading": "Carregando...",
    "common.error": "Algo deu errado",
    "common.retry": "Tentar novamente",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.back": "Voltar",
    "common.next": "Próximo",
    "common.close": "Fechar",
    "common.search": "Pesquisar",
    "common.nodata": "Nenhum dado disponível",
    "projects.loadError": "Falha ao carregar projetos",
    "projects.tryAgain": "Tentar novamente",
    "projects.emptySubtitleLong": "Crie seu primeiro projeto ou conecte via WhatsApp para configurar automaticamente.",
    "projects.createNew": "Criar Novo Projeto",
    "projects.orWhatsApp": "Ou envie WhatsApp para",
    "projects.toGetStarted": "para começar.",
    "projects.backToProjects": "Voltar aos Projetos",
    "projects.createFirst": "Crie seu primeiro projeto",
    "projects.selectProjectBudget": "Selecione um projeto na barra lateral ou no painel para ver orçamento e despesas.",
    "projects.createFirstBudget": "Crie seu primeiro projeto para acompanhar orçamento e despesas.",
    "projects.toastCreated": "Projeto criado",
    "projects.toastCreatedDesc": "foi criado com sucesso.",
    "projects.createFailed": "Falha ao criar projeto",
    "projects.modalTitle": "Novo Projeto",
    "projects.projectName": "Nome do projeto",
    "projects.projectType": "Tipo de projeto",
    "projects.residential": "Residencial",
    "projects.commercial": "Comercial",
    "projects.other": "Outro",
    "projects.locationPlaceholder": "Cidade ou endereço",
    "projects.startDate": "Data de início",
    "projects.totalBudgetUgx": "Orçamento total (UGX)",
    "projects.whatsappLink": "Número do WhatsApp para vincular",
    "projects.creating": "Criando…",
    "projects.createProject": "Criar Projeto",
    "budget.noProjectSelect": "Selecione um projeto na barra lateral ou no painel para ver orçamento e despesas.",
    "budget.noProjectCreate": "Crie seu primeiro projeto para acompanhar orçamento e despesas.",
    "budget.budgetUsed": "Orçamento usado",
    "budget.weeklyBurn": "Gasto semanal",
    "budget.weeksRemaining": "Semanas restantes",
    "budget.noExpensesHint": "Envie 'Bought cement for 200,000' via WhatsApp para começar.",
    "budget.noSpendingYet": "Nenhum histórico de gastos ainda.",
    "budget.noSpendingHint": "Registre despesas via WhatsApp para ver tendências mensais.",
    "budget.cumulativeCosts": "Custos Acumulados ao Longo do Tempo",
    "budget.noCumulativeHint": "Envie uma despesa via WhatsApp para ver seu gasto acumulado.",
    "budget.noTransactions": "Nenhuma transação ainda.",
    "budget.noTransactionsHint": "Registre uma despesa via WhatsApp ou no painel para ver aqui.",
    "budget.noVendorYet": "Nenhum dado de fornecedor ainda.",
    "budget.noVendorHint": "Despesas com nome de fornecedor aparecerão aqui.",
    "budget.date": "Data",
    "budget.desc": "Descrição",
    "budget.amount": "Valor",
    "budget.category": "Categoria",
    "budget.source": "Fonte",
    "budget.manual": "Manual",
    "materials.noProjectSelect": "Nenhum projeto selecionado. Selecione um projeto na barra lateral ou no painel.",
    "materials.noProjectCreate": "Crie seu primeiro projeto para acompanhar materiais e inventário.",
    "materials.totalMaterials": "Total de Materiais",
    "materials.lowStockItems": "Itens com Estoque Baixo",
    "materials.lastUpdated": "Última Atualização",
    "materials.restockHint": "Considere reabastecer estes materiais.",
    "materials.allWellStocked": "Todos os materiais em estoque",
    "materials.low": "Baixo",
    "materials.good": "Bom",
    "materials.medium": "Médio",
    "materials.lastUpdatedLabel": "Última atualização",
    "materials.emptyHint": "Envie 'Received 50 bags cement' ou 'Used 5 bags for foundation' via WhatsApp.",
    "daily.noProjectSelect": "Nenhum projeto selecionado. Selecione um projeto na barra lateral ou no painel.",
    "daily.noProjectCreate": "Crie seu primeiro projeto para registrar atualizações diárias.",
    "daily.activeToday": "Ativo hoje",
    "daily.noUpdatesYet": "Sem atualizações ainda",
    "daily.workersLogged": "trabalhadores registrados",
    "daily.activeDays": "Dias Ativos",
    "daily.thisWeek": "Esta Semana",
    "daily.photos": "Fotos",
    "daily.activity60": "Atividade (Últimos 60 Dias)",
    "daily.recentActivity": "Atividade Recente",
    "daily.sitePhotos": "Fotos do Local",
    "daily.noPhotosYet": "Nenhuma foto ainda.",
    "daily.noPhotosHint": "Envie fotos do local via WhatsApp para ver aqui.",
    "daily.emptyHint": "Envie '6 workers on site today' ou 'Foundation 80% complete' via WhatsApp.",
    "trends.noProjectSelect": "Nenhum projeto selecionado. Selecione um projeto na barra lateral ou no painel.",
    "trends.noProjectCreate": "Crie seu primeiro projeto para ver tendências e insights.",
    "trends.alertsAnomalies": "Alertas e Anomalias",
    "trends.noSpendingData": "Nenhum dado de gastos ainda.",
    "trends.noWorkerData": "Nenhum dado de trabalhadores ainda.",
    "trends.avg": "Média",
    "trends.peak": "Pico",
    "trends.topVendors": "Principais Fornecedores",
    "trends.noMaterialsData": "Nenhum dado de materiais ainda.",
    "trends.increasing": "Aumentando",
    "trends.decreasing": "Diminuindo",
    "trends.stable": "Estável",
    "help.howToUseTitle": "Ajuda e Como Usar",
    "help.howToUseJenga": "Como Usar o JengaTrack",
    "help.saveNumber": "Salve nosso número do WhatsApp:",
    "help.sendJoin": "Envie \"{code}\" para entrar no sandbox e começar",
    "help.textUpdates": "Envie despesas, materiais e atualizações diárias em linguagem simples",
    "help.receiptPhotos": "Envie fotos de recibos para digitalização OCR automática",
    "help.voiceNotes": "Envie notas de voz para transcrição e registro",
    "help.commandsLike": "Use comandos como \"How much have we spent?\" para resumos de orçamento",
    "help.whatsappLabel": "Número do WhatsApp para mensagens:",
    "help.joinCodeLabel": "Código para entrar no sandbox:",
    "help.commandsRefTitle": "Referência de Comandos do WhatsApp",
    "help.whatToSay": "O que dizer",
    "help.whatHappens": "O que acontece",
    "help.faqAddManager": "Como adiciono meu gerente para acompanhar atualizações?",
    "help.faqAddManagerAns": "Compartilhe o número do WhatsApp com seu gerente. Eles começam a enviar mensagens e o bot cuida do resto.",
    "help.faqDashboard": "Com que frequência o painel é atualizado?",
    "help.faqDashboardAns": "A cada 30 segundos automaticamente.",
    "help.faqVoice": "Posso usar notas de voz?",
    "help.faqVoiceAns": "Sim! Envie qualquer nota de voz e o bot irá transcrever e processar.",
    "help.faqCurrencies": "Quais moedas são suportadas?",
    "help.faqCurrenciesAns": "UGX (Uganda), KES (Quênia), NGN (Nigéria). Fotos de recibos convertem automaticamente para UGX.",
    "help.cmdExpense": "Registra despesa",
    "help.cmdInventory": "Atualiza inventário",
    "help.cmdDaily": "Registra atividade diária",
    "help.cmdProgress": "Atualiza progresso",
    "help.cmdBudget": "Resumo do orçamento",
    "help.cmdInventoryCheck": "Verificar inventário",
    "help.cmdDelay": "Registra atraso",
    "help.cmdSwitch": "Mudar projeto ativo",
    "help.cmdOCR": "Digitalização OCR",
    "help.cmdVoice": "Transcrever e registrar",
    "auth.login.signingIn": "Entrando…",
    "auth.login.signupLink": "Cadastrar-se",
    "auth.register.whatsapp": "Número do WhatsApp",
    "auth.register.confirmPassword": "Confirmar Senha",
    "auth.register.creating": "Criando conta…",
    "auth.register.strength.weak": "Fraca",
    "auth.register.strength.fair": "Razoável",
    "auth.register.strength.good": "Boa",
    "auth.register.strength.strong": "Forte",
    "auth.password.requirement.length": "Pelo menos 8 caracteres",
    "auth.password.requirement.lowercase": "Uma letra minúscula",
    "auth.password.requirement.uppercase": "Uma letra maiúscula",
    "auth.password.requirement.digit": "Um número",
    "auth.password.requirement.symbol": "Um símbolo (!@#$…)",
    "settings.passwordHint": "Senha atual obrigatória. A nova senha deve seguir as mesmas regras do cadastro.",
    "auth.forgotPassword.tagline": "Vamos te ajudar.",
    "auth.forgotPassword.title": "Redefinir sua senha",
    "auth.forgotPassword.subtitle": "Insira seu e-mail e enviaremos um link de redefinição",
    "auth.forgotPassword.button": "Enviar Link",
    "auth.forgotPassword.sending": "Enviando…",
    "auth.forgotPassword.backToLogin": "Voltar para login",
    "auth.forgotPassword.checkInbox": "Verifique sua caixa de entrada",
    "auth.forgotPassword.resend": "Não recebeu? Reenviar",
    "auth.forgotPassword.resending": "Reenviando…",
    "help.centerTitle": "Central de Ajuda",
    "help.tagline": "Tudo que você precisa para aproveitar o JengaTrack.",
    "help.searchPlaceholder": "Pesquisar ajuda...",
    "help.whatsappBot": "Bot do WhatsApp",
    "help.whatsappBotDesc": "Comece a conversar agora",
    "help.openChat": "Abrir Chat",
    "help.viewDashboard": "Ver Painel",
    "help.viewDashboardDesc": "Ir para o seu projeto",
    "help.goNow": "Ir agora",
    "help.sendFeedback": "Enviar Feedback",
    "help.sendFeedbackDesc": "Reportar um bug ou sugestão",
    "help.emailUs": "Envie-nos um e-mail",
    "help.getStarted": "Comece em 3 Passos",
    "help.step1Title": "Crie seu projeto",
    "help.step1Desc": "Cadastre-se e crie seu primeiro projeto de construção com orçamento e localização.",
    "help.step2Title": "Conectar WhatsApp",
    "help.step2Desc": "Salve nosso número e envie sua primeira mensagem para vincular sua conta.",
    "help.step3Title": "Comece a registrar",
    "help.step3Desc": "Envie despesas, materiais, trabalhadores e fotos diretamente pelo WhatsApp.",
    "help.commandsDesc": "Digite naturalmente — aqui estão alguns exemplos:",
    "help.faqTitle": "Perguntas Frequentes",
    "help.noResults": "Nenhum resultado para",
    "help.stillNeedHelp": "Ainda precisa de ajuda?",
    "help.supportDesc": "Nossa equipe está disponível via WhatsApp durante horário comercial.",
    "help.chatOnWhatsapp": "Conversar no WhatsApp",
    "help.emailSupport": "Suporte por E-mail",
    "help.responseTime": "Tempo médio de resposta: menos de 2 horas",
    "settings.subheader": "Gerencie as configurações do projeto e detalhes do perfil.",
    "settings.linkWhatsapp": "Vincular WhatsApp",
    "settings.linkWhatsappDesc": "Criou um projeto pelo WhatsApp? Vincule seu número para sincronizar.",
    "settings.link": "Vincular",
    "settings.description": "Descrição",
    "settings.channelType": "Tipo de Canal",
    "settings.directMessage": "Mensagem Direta",
    "settings.groupChat": "Chat em Grupo",
    "settings.saveProfile": "Salvar Perfil",
    "settings.changePassword": "Alterar Senha",
    "settings.completeProject": "Concluir Projeto",
    "settings.markAsCompleted": "Marcar como Concluído",
    "settings.markCompleted": "Marcar Concluído",
    "settings.passwordUpdated": "Senha atualizada com sucesso.",
    "settings.currentPassword": "Senha Atual",
    "settings.newPassword": "Nova Senha",
    "settings.confirmNewPassword": "Confirmar Nova Senha",
    "settings.statusActive": "Ativo",
    "settings.statusCompleted": "Concluído",
    "settings.statusOnHold": "Em Espera",
    "materials.addMaterial": "Adicionar material",
    "materials.headerSubtitle": "Inventário por material — níveis de estoque, valor e alertas.",
    "materials.autoSync": "Sincronizado com WhatsApp — materiais registrados via chat aparecem aqui instantaneamente.",
    "materials.lastSynced": "Última sincronização:",
    "materials.noMaterials": "Nenhum material registrado ainda.",
    "materials.noMaterialsDesc": "Os materiais aparecem aqui automaticamente quando você registra compras via WhatsApp, ou adicione-os manualmente.",
    "materials.addFirst": "Adicionar primeiro material",
    "materials.colName": "Nome",
    "materials.colCurrentStock": "Estoque atual",
    "materials.colUnitCost": "Custo unitário",
    "materials.colTotalValue": "Valor total",
    "materials.colLastPurchased": "Última compra",
    "materials.colStatus": "Status",
    "materials.colStockLevel": "Nível de estoque",
    "materials.colActions": "Ações",
    "materials.outOfStock": "Sem Estoque",
    "materials.lowStock": "Estoque Baixo",
    "materials.inStock": "Em Estoque",
    "materials.editMaterialTitle": "Editar material",
    "materials.editDesc": "Atualize quantidade, custos e limite de estoque baixo.",
    "materials.addDesc": "Adicione estoque ao inventário.",
    "materials.nameLbl": "Nome",
    "materials.quantityLbl": "Quantidade",
    "materials.unitLbl": "Unidade",
    "materials.unitCostLbl": "Custo unitário",
    "materials.thresholdLbl": "Limite de estoque baixo",
    "materials.removeTitle": "Remover material?",
    "materials.removeSaving": "Removendo…",
    "materials.totalInventoryValue": "Valor total do inventário",
    "projects.startFirst": "Comece criando seu primeiro projeto.",
    "projects.searchPlaceholder": "Pesquisar projetos por nome ou localização…",
    "projects.sortDate": "Ordenar: Data atualizada",
    "projects.sortName": "Ordenar: Nome",
    "projects.sortProgress": "Ordenar: Progresso",
    "projects.sortBudget": "Ordenar: Orçamento",
    "projects.noMatchTitle": "Sem correspondências",
    "projects.logFromWhatsapp": "Registrar pelo WhatsApp",
    "projects.chatOnWhatsapp": "Conversar no WhatsApp",
    "projects.couldntLoad": "Não foi possível carregar os projetos",
    "projects.kpiTotalProjects": "Total de Projetos",
    "projects.kpiTotalBudget": "Orçamento Total",
    "projects.kpiTotalSpent": "Total Gasto",
    "projects.kpiActiveSites": "Obras Ativas",
    "projects.kpiAcrossAll": "Em todos os projetos",
    "common.retry": "Tentar novamente",
    "common.cancel": "Cancelar",
    "common.saving": "Salvando…",
    "common.save": "Salvar",
    "common.delete": "Excluir",
    "common.refresh": "Atualizar",
    "daily.header": "Prestação de Contas Diária",
    "daily.subheader": "Acompanhe o progresso do canteiro, presença de trabalhadores e condições diárias.",
    "daily.daysRecorded": "dias registrados",
    "daily.daysInARow": "dias seguidos",
    "daily.perDay": "por dia",
    "daily.captured": "capturadas",
    "daily.daySummary": "Resumo do dia",
    "daily.workersOnSite": "trabalhadores no canteiro",
    "daily.weather": "Tempo:",
    "daily.notes": "Notas:",
    "daily.failedToLoad": "Falha ao carregar entradas.",
    "daily.noWhatsappReports": "Nenhum relatório do WhatsApp para este dia.",
    "daily.showAllActivity": "Mostrar todas as atividades",
    "daily.noActivity": "Nenhuma atividade registrada para este dia.",
    "daily.logActivity": "Registrar Atividade",
    "daily.activityLast60": "Atividade — últimos 60 dias",
    "daily.logActivityTitle": "Registrar Atividade",
    "daily.recordWhatHappened": "Registre o que aconteceu em",
    "daily.entry": "Entrada",
    "daily.remove": "Remover",
    "daily.addAnotherEntry": "+ Adicionar outra entrada",
    "daily.saveActivity": "Salvar Atividade",
    "daily.viewAll": "Ver tudo",
    "daily.viewHeatmap": "Ver mapa de calor",
    "daily.chatReports": "Relatórios de Chat",
    "daily.photos": "Fotos",
    "daily.activityType.labourPayment": "Pagamento de mão de obra",
    "daily.activityType.delivery": "Entrega",
    "daily.activityType.taskCompletion": "Conclusão de tarefa",
    "daily.activityType.mediaUpload": "Upload de mídia",
    "daily.activityType.staffing": "Equipe",
    "daily.activityType.financials": "Financeiro",
    "daily.activityType.activity": "Atividade",
  },
};

function getStoredLanguage(): Language {
  if (typeof window === "undefined") return "en";
  try {
    const saved = localStorage.getItem("jenga_language");
    if (saved === "en" || saved === "lg" || saved === "pt") return saved;
  } catch {
    // ignore
  }
  return "en";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getStoredLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("jenga_language", lang);
    } catch {
      // ignore
    }
  };

  const t = (key: string): string => {
    const map = translations[language];
    const fallback = translations.en;
    return (map && map[key]) || (fallback && fallback[key]) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (ctx === undefined) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
