"use client";

import {
  createContext,
  useContext,
  useState,
  type ReactNode,
} from "react";

export type Language = "en" | "lg" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.budgets": "Budgets & Costs",
    "nav.materials": "Materials & Supplies",
    "nav.daily": "Daily Accountability",
    "nav.trends": "Trends & Insights",
    "nav.projects": "My Projects",
    "nav.settings": "Settings",
    "nav.help": "Help",
    "nav.logout": "Logout",
    "nav.more": "More",
    "landing.hero.title": "Message Anywhere.\nMonitor Everywhere.",
    "landing.hero.subtitle": "Use your favorite chat app to manage your construction project.",
    "landing.hero.cta": "Start Tracking",
    "landing.hero.demo": "Learn More",
    "landing.features.title": "Turn Site Messages Into\nStructured Control",
    "landing.features.subtitle": "JengaTrack transforms everyday construction updates into organized trackable data.",
    "landing.howitworks.title": "How It Works",
    "landing.howitworks.step1": "Send site updates",
    "landing.howitworks.step2": "Data Updates Automatically",
    "landing.howitworks.step3": "View or Request Insights",
    "landing.cta.title": "Build Smarter from Day One",
    "landing.cta.button": "Submit",
    "auth.login.title": "Welcome Back",
    "auth.login.subtitle": "Log in to manage your construction projects",
    "auth.login.email": "Email Address",
    "auth.login.password": "Password",
    "auth.login.button": "Sign In",
    "auth.login.forgot": "Forgot password?",
    "auth.login.noaccount": "Don't have an account?",
    "auth.login.create": "Create one",
    "auth.register.title": "Create Account",
    "auth.register.subtitle": "Start managing your projects today",
    "auth.register.name": "Full Name",
    "auth.register.email": "Email Address",
    "auth.register.password": "Password",
    "auth.register.button": "Create Account",
    "auth.register.hasaccount": "Already have an account?",
    "auth.register.signin": "Sign in",
    "projects.title": "My Projects",
    "projects.new": "New Project",
    "projects.empty.title": "No projects yet",
    "projects.empty.subtitle": "Create your first project or\nconnect via WhatsApp",
    "projects.spent": "spent of",
    "projects.lastupdate": "Last update",
    "projects.noupdate": "No updates yet",
    "projects.active": "Active",
    "projects.completed": "Completed",
    "projects.select": "Select project",
    "dashboard.title": "Project Dashboard",
    "dashboard.progress": "Overall Progress",
    "dashboard.schedule": "Schedule Status",
    "dashboard.budget": "Budget Health",
    "dashboard.issues": "Active Issues",
    "dashboard.ontrack": "On Track",
    "dashboard.atrisk": "At Risk",
    "dashboard.delayed": "Delayed",
    "dashboard.allclear": "All clear ✅",
    "dashboard.lastupdate": "Last updated",
    "budget.title": "Budgets & Costs",
    "budget.total": "Total Budget",
    "budget.spent": "Total Spent",
    "budget.remaining": "Remaining",
    "budget.breakdown": "Budget Breakdown",
    "budget.monthly": "Spending by Month",
    "budget.recent": "Recent Transactions",
    "budget.vendors": "Vendor Breakdown",
    "budget.noexpenses": "No expenses logged yet",
    "materials.title": "Materials & Supplies",
    "materials.inventory": "Inventory",
    "materials.lowstock": "Low Stock Alerts",
    "materials.allgood": "✅ All materials well stocked",
    "materials.empty": "No materials tracked yet",
    "daily.title": "Daily Accountability",
    "daily.today": "Today's Status",
    "daily.active": "Active today",
    "daily.inactive": "No updates yet",
    "daily.workers": "Workers on site",
    "daily.streak": "Current Streak",
    "daily.totaldays": "Total Active Days",
    "daily.avgworkers": "Avg Workers/Day",
    "daily.empty": "No daily updates yet",
    "trends.title": "Trends & Insights",
    "trends.spending": "Spending Trend",
    "trends.workers": "Worker Activity",
    "trends.materials": "Materials Usage",
    "trends.predictions": "Predictions",
    "trends.alerts": "Alerts",
    "trends.noissues": "✅ No issues detected",
    "trends.burnrate": "Weekly Burn Rate",
    "trends.runout": "Budget Runout Estimate",
    "trends.completion": "Project Completion",
    "trends.empty": "Trends will appear after a few\ndays of WhatsApp updates",
    "settings.title": "Settings",
    "settings.project": "Project Settings",
    "settings.profile": "Profile Settings",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.save": "Save Changes",
    "settings.saved": "Settings saved! ✅",
    "settings.danger": "Danger Zone",
    "settings.complete": "Mark project as completed",
    "settings.completeConfirm": "Mark project as completed?",
    "settings.completeDescription": "This will set the project status to completed. You won't be able to log new expenses or daily updates. You can still view all data.",
    "settings.completeConfirmButton": "Yes, mark as completed",
    "settings.projectname": "Project Name",
    "settings.location": "Location",
    "settings.budget": "Total Budget (UGX)",
    "settings.status": "Project Status",
    "settings.whatsapp": "WhatsApp Number",
    "settings.displayname": "Display Name",
    "settings.languageHint": "Select your preferred language",
    "settings.languageHintExtra": "Chagua lugha yako / Escolha seu idioma",
    "help.title": "Help & Support",
    "help.commands": "WhatsApp Commands",
    "help.faq": "FAQ",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.retry": "Try again",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.back": "Back",
    "common.next": "Next",
    "common.close": "Close",
    "common.search": "Search",
    "common.nodata": "No data available",
  },
  lg: {
    "nav.dashboard": "Pulezidenti",
    "nav.budgets": "Ensimbi n'Empaliro",
    "nav.materials": "Ebintu n'Eby'okuzimba",
    "nav.daily": "Ebikolwa bya Buli Lunaku",
    "nav.trends": "Endabika n'Okunoonyereza",
    "nav.projects": "Emirimu Gyange",
    "nav.settings": "Entegeka",
    "nav.help": "Obuyamba",
    "nav.logout": "Funa",
    "nav.more": "Ebirala",
    "landing.hero.title": "Tuma Okubiri.\nLaba Wonna.",
    "landing.hero.subtitle": "Kozesa chat app yo okutebeza omurimo gwo gw'okuzimba.",
    "landing.hero.cta": "Tandika Okukwata",
    "landing.hero.demo": "Soma Ebirala",
    "landing.features.title": "Tebeza Emirimu gy'Okuzimba\nKu WhatsApp",
    "landing.features.subtitle": "JengaTrack ekyusa ennunula z'okuzimba mu data eteekateekeddwa.",
    "landing.howitworks.title": "Engeri Gye Ikola",
    "landing.howitworks.step1": "Tuma obubaka bwa WhatsApp",
    "landing.howitworks.step2": "Bot ekola ku bubaka bwo",
    "landing.howitworks.step3": "Dashboard enunulwa mangu",
    "landing.cta.title": "Tandika Ofudde",
    "landing.cta.button": "Tuma",
    "auth.login.title": "Tuukirira Nate",
    "auth.login.subtitle": "Yingira okutebeza emirimu gy'okuzimba",
    "auth.login.email": "Endagiriro y'Email",
    "auth.login.password": "Ekigambo ky'Okulinda",
    "auth.login.button": "Yingira",
    "auth.login.forgot": "Werabira ekigambo ky'okulinda?",
    "auth.login.noaccount": "Tolina kkaawunti?",
    "auth.login.create": "Tonda emu",
    "auth.register.title": "Tonda Kkaawunti",
    "auth.register.subtitle": "Tandika okutebeza emirimu gyo leero",
    "auth.register.name": "Erinnya Lyo Lyonna",
    "auth.register.email": "Endagiriro y'Email",
    "auth.register.password": "Ekigambo ky'Okulinda",
    "auth.register.button": "Tonda Kkaawunti",
    "auth.register.hasaccount": "Olina kkaawunti?",
    "auth.register.signin": "Yingira",
    "projects.title": "Emirimu Gyange",
    "projects.new": "Omurimo Omupya",
    "projects.empty.title": "Terina mirimo nawo",
    "projects.empty.subtitle": "Tonda omurimo gwo ogwa kubanga\noba gangana ku WhatsApp",
    "projects.spent": "yatumiibwa mu",
    "projects.lastupdate": "Ennunula ya omuvubuka",
    "projects.noupdate": "Terina nnunula nawo",
    "projects.active": "Yatandika",
    "projects.completed": "Yaggwaako",
    "projects.select": "Londa omurimo",
    "dashboard.title": "Pulezidenti w'Omurimo",
    "dashboard.progress": "Enkola Yonna",
    "dashboard.schedule": "Endabika y'Enteekateeka",
    "dashboard.budget": "Obulamu bw'Ensimbi",
    "dashboard.issues": "Ebizibu Ebiriko",
    "dashboard.ontrack": "Ku Kkubo",
    "dashboard.atrisk": "Mu Kabi",
    "dashboard.delayed": "Kuziyizibwa",
    "dashboard.allclear": "Buli kimu kituufu ✅",
    "dashboard.lastupdate": "Ennunula ya omuvubuka",
    "budget.title": "Ensimbi n'Empaliro",
    "budget.total": "Ensimbi Zonna",
    "budget.spent": "Ensimbi Ezatumiibwa",
    "budget.remaining": "Ezasigalawo",
    "budget.breakdown": "Okugabana kw'Ensimbi",
    "budget.monthly": "Okutumiibwa mu Mwezi",
    "budget.recent": "Obusuubuzi Obwakiiro",
    "budget.vendors": "Abatundisi Abalala",
    "budget.noexpenses": "Terina nsimbi yatumiibwa",
    "materials.title": "Ebintu n'Eby'okuzimba",
    "materials.inventory": "Ebintu Ebiriwo",
    "materials.lowstock": "Okumenyeeza kw'Ebintu",
    "materials.allgood": "✅ Ebintu byonna biriwo",
    "materials.empty": "Terina bintu byakwatibwa",
    "daily.title": "Ebikolwa bya Buli Lunaku",
    "daily.today": "Endabika ya Leero",
    "daily.active": "Ekola leero",
    "daily.inactive": "Terina nnunula nawo",
    "daily.workers": "Abakoozi Ku Kifo",
    "daily.streak": "Ennaku Entalirivu",
    "daily.totaldays": "Ennaku Zonna Ezikoleddwa",
    "daily.avgworkers": "Ab'okulaba mu lunaku",
    "daily.empty": "Terina bikolwa bya buli lunaku",
    "trends.title": "Endabika n'Okunoonyereza",
    "trends.spending": "Endabika y'Okutumiibwa",
    "trends.workers": "Ebikolwa by'Abakoozi",
    "trends.materials": "Okutumiibwa kw'Ebintu",
    "trends.predictions": "Okubuulira Ebizaajja",
    "trends.alerts": "Okumenyeeza",
    "trends.noissues": "✅ Terina bizibu byakiririzibwa",
    "trends.burnrate": "Enkola y'Ensimbi mu Wiiki",
    "trends.runout": "Ensimbi Mazima Lini",
    "trends.completion": "Omurimo Gwagwaako Lini",
    "trends.empty": "Endabika ejja ng'olaba ennaku\nennaka ez'ennunula ku WhatsApp",
    "settings.title": "Entegeka",
    "settings.project": "Entegeka y'Omurimo",
    "settings.profile": "Entegeka y'Omuntu",
    "settings.language": "Olulimi",
    "settings.theme": "Endabika",
    "settings.save": "Zachora Ennunula",
    "settings.saved": "Entegeka Zachoredwa! ✅",
    "settings.danger": "Ekifo Ky'Obubuubi",
    "settings.complete": "Labika omurimo gwagwaako",
    "settings.completeConfirm": "Labika omurimo gwagwaako?",
    "settings.completeDescription": "Omurimo gujja kukolebwa nga gwagwaako. Toliba kuwandiika nsimbi ennunula oba ennunula z'ennaku. Kyokka osobola okulaba data yonna.",
    "settings.completeConfirmButton": "Yee, labika gwagwaako",
    "settings.projectname": "Erinnya ly'Omurimo",
    "settings.location": "Ekifo",
    "settings.budget": "Ensimbi Zonna (UGX)",
    "settings.status": "Endabika y'Omurimo",
    "settings.whatsapp": "Namba ya WhatsApp",
    "settings.displayname": "Erinnya ly'Okulagirako",
    "settings.languageHint": "Londa olulimi lwo",
    "settings.languageHintExtra": "Chagua lugha yako / Escolha seu idioma",
    "help.title": "Obuyamba n'Enyigiriza",
    "help.commands": "Ebiragiro bya WhatsApp",
    "help.faq": "Ebibuuzo Ebibuuzibwa Ennyi",
    "common.loading": "Tekebeza...",
    "common.error": "Wabaawo ekizibu",
    "common.retry": "Gezaako Nate",
    "common.save": "Zachora",
    "common.cancel": "Sazaamu",
    "common.confirm": "Kakasa",
    "common.delete": "Sazaamu",
    "common.edit": "Kyusa",
    "common.back": "Ddayo Eweyo",
    "common.next": "Endeera",
    "common.close": "Ggalawo",
    "common.search": "Noonya",
    "common.nodata": "Terina data nawo",
  },
  pt: {
    "nav.dashboard": "Painel",
    "nav.budgets": "Orçamentos e Custos",
    "nav.materials": "Materiais e Suprimentos",
    "nav.daily": "Prestação de Contas Diária",
    "nav.trends": "Tendências e Insights",
    "nav.projects": "Meus Projetos",
    "nav.settings": "Configurações",
    "nav.help": "Ajuda",
    "nav.logout": "Sair",
    "nav.more": "Mais",
    "landing.hero.title": "Mensagem em Qualquer Lugar.\nMonitore em Todo Lugar.",
    "landing.hero.subtitle": "Use seu app de chat favorito para gerenciar seu projeto de construção.",
    "landing.hero.cta": "Começar a Rastrear",
    "landing.hero.demo": "Saiba Mais",
    "landing.features.title": "Gerencie Projetos de Construção\npelo WhatsApp",
    "landing.features.subtitle": "Rastreie orçamentos, materiais e progresso diário — tudo pelo WhatsApp.",
    "landing.howitworks.title": "Como Funciona",
    "landing.howitworks.step1": "Envie uma mensagem no WhatsApp",
    "landing.howitworks.step2": "Bot processa sua atualização",
    "landing.howitworks.step3": "Painel atualiza instantaneamente",
    "landing.cta.title": "Construa com Inteligência desde o Primeiro Dia",
    "landing.cta.button": "Enviar",
    "auth.login.title": "Bem-vindo de Volta",
    "auth.login.subtitle": "Faça login para gerenciar seus projetos de construção",
    "auth.login.email": "Endereço de E-mail",
    "auth.login.password": "Senha",
    "auth.login.button": "Entrar",
    "auth.login.forgot": "Esqueceu a senha?",
    "auth.login.noaccount": "Não tem uma conta?",
    "auth.login.create": "Criar uma",
    "auth.register.title": "Criar Conta",
    "auth.register.subtitle": "Comece a gerenciar seus projetos hoje",
    "auth.register.name": "Nome Completo",
    "auth.register.email": "Endereço de E-mail",
    "auth.register.password": "Senha",
    "auth.register.button": "Criar Conta",
    "auth.register.hasaccount": "Já tem uma conta?",
    "auth.register.signin": "Entrar",
    "projects.title": "Meus Projetos",
    "projects.new": "Novo Projeto",
    "projects.empty.title": "Nenhum projeto ainda",
    "projects.empty.subtitle": "Crie seu primeiro projeto ou\nconecte via WhatsApp",
    "projects.spent": "gasto de",
    "projects.lastupdate": "Última atualização",
    "projects.noupdate": "Sem atualizações ainda",
    "projects.active": "Ativo",
    "projects.completed": "Concluído",
    "projects.select": "Selecionar projeto",
    "dashboard.title": "Painel do Projeto",
    "dashboard.progress": "Progresso Geral",
    "dashboard.schedule": "Status do Cronograma",
    "dashboard.budget": "Saúde do Orçamento",
    "dashboard.issues": "Problemas Ativos",
    "dashboard.ontrack": "No Prazo",
    "dashboard.atrisk": "Em Risco",
    "dashboard.delayed": "Atrasado",
    "dashboard.allclear": "Tudo certo ✅",
    "dashboard.lastupdate": "Última atualização",
    "budget.title": "Orçamentos e Custos",
    "budget.total": "Orçamento Total",
    "budget.spent": "Total Gasto",
    "budget.remaining": "Restante",
    "budget.breakdown": "Detalhamento do Orçamento",
    "budget.monthly": "Gastos por Mês",
    "budget.recent": "Transações Recentes",
    "budget.vendors": "Detalhamento por Fornecedor",
    "budget.noexpenses": "Nenhuma despesa registrada",
    "materials.title": "Materiais e Suprimentos",
    "materials.inventory": "Inventário",
    "materials.lowstock": "Alertas de Estoque Baixo",
    "materials.allgood": "✅ Todos os materiais em estoque",
    "materials.empty": "Nenhum material rastreado ainda",
    "daily.title": "Prestação de Contas Diária",
    "daily.today": "Status de Hoje",
    "daily.active": "Ativo hoje",
    "daily.inactive": "Sem atualizações ainda",
    "daily.workers": "Trabalhadores no Local",
    "daily.streak": "Sequência Atual",
    "daily.totaldays": "Total de Dias Ativos",
    "daily.avgworkers": "Média de Trabalhadores/Dia",
    "daily.empty": "Nenhuma atualização diária ainda",
    "trends.title": "Tendências e Insights",
    "trends.spending": "Tendência de Gastos",
    "trends.workers": "Atividade de Trabalhadores",
    "trends.materials": "Uso de Materiais",
    "trends.predictions": "Previsões",
    "trends.alerts": "Alertas",
    "trends.noissues": "✅ Nenhum problema detectado",
    "trends.burnrate": "Taxa de Gasto Semanal",
    "trends.runout": "Estimativa de Esgotamento",
    "trends.completion": "Conclusão do Projeto",
    "trends.empty": "Tendências aparecerão após alguns\ndias de atualizações no WhatsApp",
    "settings.title": "Configurações",
    "settings.project": "Configurações do Projeto",
    "settings.profile": "Configurações do Perfil",
    "settings.language": "Idioma",
    "settings.theme": "Tema",
    "settings.save": "Salvar Alterações",
    "settings.saved": "Configurações salvas! ✅",
    "settings.danger": "Zona de Perigo",
    "settings.complete": "Marcar projeto como concluído",
    "settings.completeConfirm": "Marcar projeto como concluído?",
    "settings.completeDescription": "Isso definirá o status do projeto como concluído. Você não poderá registrar novas despesas ou atualizações diárias. Ainda poderá ver todos os dados.",
    "settings.completeConfirmButton": "Sim, marcar como concluído",
    "settings.projectname": "Nome do Projeto",
    "settings.location": "Localização",
    "settings.budget": "Orçamento Total (UGX)",
    "settings.status": "Status do Projeto",
    "settings.whatsapp": "Número do WhatsApp",
    "settings.displayname": "Nome de Exibição",
    "settings.languageHint": "Selecione seu idioma preferido",
    "settings.languageHintExtra": "Chagua lugha yako / Escolha seu idioma",
    "help.title": "Ajuda e Suporte",
    "help.commands": "Comandos do WhatsApp",
    "help.faq": "Perguntas Frequentes",
    "common.loading": "Carregando...",
    "common.error": "Algo deu errado",
    "common.retry": "Tentar novamente",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.back": "Voltar",
    "common.next": "Próximo",
    "common.close": "Fechar",
    "common.search": "Pesquisar",
    "common.nodata": "Nenhum dado disponível",
  },
};

function getStoredLanguage(): Language {
  if (typeof window === "undefined") return "en";
  try {
    const saved = localStorage.getItem("jenga_language");
    if (saved === "en" || saved === "lg" || saved === "pt") return saved;
  } catch {
    // ignore
  }
  return "en";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getStoredLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("jenga_language", lang);
    } catch {
      // ignore
    }
  };

  const t = (key: string): string => {
    const map = translations[language];
    const fallback = translations.en;
    return (map && map[key]) || (fallback && fallback[key]) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (ctx === undefined) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
